# This -*- perl -*- script writes the Makefile for Lingua::EN::Numbers::Ordinate
# Time-stamp: "2000-08-24 17:14:02 MDT"
# See lib/ExtUtils/MakeMaker.pm for details of how to influence
# the contents of the Makefile that is written.
require 5.004;
use strict;
use ExtUtils::MakeMaker;

WriteMakefile(
    'NAME'	=> 'Lingua::EN::Numbers::Ordinate',
    'VERSION_FROM' => 'Ordinate.pm', # finds $VERSION
    'dist'        => { COMPRESS => 'gzip -9f', SUFFIX => 'gz', },
);

package MY;

sub libscan
{ # Determine things that should *not* be installed
    my($self, $path) = @_;
    return '' if $path =~ m/~/;
    $path;
}

__END__
